import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA, VitePWAOptions } from 'vite-plugin-pwa';
import manifest from './manifest.json';

// Extract PWA options into a constant for better readability
const pwaOptions: Partial<VitePWAOptions> = {
  registerType: 'autoUpdate',
  manifest,
  workbox: {
    // Ensure all assets generated by Vite are cached.
    globPatterns: ['**/*.{js,css,html,svg,png,ico}'],
    // Strategy for caching external assets (like the Tailwind CDN)
    runtimeCaching: [
      {
        urlPattern: /^https:\/\/cdn\.tailwindcss\.com/,
        handler: 'CacheFirst',
        options: {
          cacheName: 'tailwind-cache',
          expiration: {
            maxEntries: 1,
            maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
          },
          cacheableResponse: {
            statuses: [0, 200],
          },
        },
      },
    ],
  },
};

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, '.', '');
  return {
    // The base path should match your repository name for GitHub Pages
    base: '/teleprompter-pro/',
    plugins: [react(), VitePWA(pwaOptions)],
    define: {
      'process.env.GEMINI_API_KEY': JSON.stringify(env.GEMINI_API_KEY || ''),
    },
  };
});
